# Must Be Viral - Cloudflare Workers Configuration
name = "must-be-viral"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
account_id = "d2897bdebfa128919bd89b265e6a712e"

# Environment configurations
[env.development]
name = "must-be-viral-dev"
vars = { NODE_ENV = "development", NEXT_PUBLIC_CLOUDFLARE_WORKERS_URL = "http://localhost:8787" }

[env.production]
name = "must-be-viral-prod"
vars = { NODE_ENV = "production", NEXT_PUBLIC_CLOUDFLARE_WORKERS_URL = "https://must-be-viral-prod.ernijs-ansons.workers.dev" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "must-be-viral-db"
database_id = "14bdc6aa-5ddb-4340-bfb2-59dc68d2c520"

[[env.production.kv_namespaces]]
binding = "TRENDS_CACHE"
id = "7e322b647b814e7298e38c23197c5a06"

[[env.production.r2_buckets]]
binding = "ASSETS_STORAGE"
bucket_name = "must-be-viral-assets"

[env.production.ai]
binding = "AI"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "must-be-viral-db"
database_id = "14bdc6aa-5ddb-4340-bfb2-59dc68d2c520"
migrations_dir = "migrations"

# KV Namespace for trends cache
[[kv_namespaces]]
binding = "TRENDS_CACHE"
id = "7e322b647b814e7298e38c23197c5a06"

# R2 Bucket for asset storage
[[r2_buckets]]
binding = "ASSETS_STORAGE"
bucket_name = "must-be-viral-assets"

# AI binding for Cloudflare AI
[ai]
binding = "AI"

# Environment secrets (add via wrangler secret put)
# Required secrets:
# - JWT_SECRET
# - STRIPE_SECRET_KEY
# - CLOUDFLARE_API_TOKEN

# Local development with Next.js
# Variables are now defined in the env sections above

# Build configuration for Workers
[build]
command = "npm run build"

# Pages configuration
pages_build_output_dir = "dist"

# Routes for Workers API (if using custom domain)
# routes = [
#   { pattern = "mustbeviral.com/api/*", zone_name = "mustbeviral.com" }
# ]